/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import api_assets_pokemon.*;
import api_response_classes.*;
import java.text.DecimalFormat;
import pokemon_objects.*;

/**
 *
 * @author raphaelhicaro
 */
public class Pokedex extends javax.swing.JPanel {
    private PokemonResponseDescription pokemonDescriptionResponse;
    private PokemonResponseGeneral pokemonGeneralResponse;
    
    private PokemonDescriptionObject descriptionObj;
    private PokemonPhysicalObject physicalObj;
    private API_Response_Pokemon pokedexResponse;
    
    private static final DecimalFormat df = new DecimalFormat("0");
   
    public Pokedex() {
        initComponents();
        pokemonDescriptionResponse = new PokemonResponseDescription();
        pokemonGeneralResponse = new PokemonResponseGeneral();
        
        descriptionObj = new PokemonDescriptionObject();
        physicalObj = new PokemonPhysicalObject();
        pokedexResponse = new API_Response_Pokemon();
    }
    
    public void updatePanel(String pokemonName){
        this.pokemonDescriptionResponse = pokedexResponse.
                getPokemonResponseDescription(pokemonName);
        this.pokemonGeneralResponse = pokedexResponse.
                getPokemonResponseGeneral(pokemonName);
        updatePokedex(this.pokemonDescriptionResponse,this.pokemonGeneralResponse);
    }
    
    public void updatePokedex(PokemonResponseDescription responseDescription, 
            PokemonResponseGeneral responseGeneral){
        weight.setText(df.format(responseGeneral.getWeight()));
        height.setText(df.format(responseGeneral.getHeight()));
        if (responseGeneral.getTypes().length == )
        type.setText(responseGeneral.)
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pokemonSprite = new javax.swing.JLabel();
        weightLabel = new javax.swing.JLabel();
        heightLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        weight = new javax.swing.JLabel();
        weightTypeLabel = new javax.swing.JLabel();
        height = new javax.swing.JLabel();
        heightTypeLabel = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        description = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        pokemonSprite.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        weightLabel.setText("Pokémon Weight:");

        heightLabel.setText("Pokémon Height:");

        typeLabel.setText("Pokémon Type:");

        weight.setText("##.##");

        weightTypeLabel.setText("lbs");

        height.setText("#.#");

        heightTypeLabel.setText("ft");

        type.setText("Place Holder");

        description.setBorder(javax.swing.BorderFactory.createTitledBorder("Description"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pokemonSprite, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(typeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(type))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(heightLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(height)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(heightTypeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(weightLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weightTypeLabel)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(pokemonSprite, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightLabel)
                    .addComponent(weight)
                    .addComponent(weightTypeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heightLabel)
                    .addComponent(height)
                    .addComponent(heightTypeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLabel)
                    .addComponent(type))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel description;
    private javax.swing.JLabel height;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JLabel heightTypeLabel;
    private javax.swing.JLabel pokemonSprite;
    private javax.swing.JLabel type;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel weight;
    private javax.swing.JLabel weightLabel;
    private javax.swing.JLabel weightTypeLabel;
    // End of variables declaration//GEN-END:variables
}
